### ISSUE TITLE
Geometry Editor and Add Field Data Image Editor Issues in Alpha windows

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#1207]
To recreate:

Initial Conditions, right click, add field data brings ups geometry editor; use "Field Data" button, select which species to add the field data, then a file name to save the field data as.  Geometry editor opens but is not complete.  if change size components of the editor appear/disappear, but buttons are in fact functional.  Image of what you see is here, then User log example for this error is below that:

![image](https://github.com/virtualcell/vcell/assets/53492064/f6c2dd29-ab6f-4c8f-9583-2407f1020375)

Error: Could not find mediaLib accelerator wrapper classes. Continuing in pure Java mode.
Occurs in: com.sun.media.jai.mlib.MediaLibAccessor
java.lang.NoClassDefFoundError: com/sun/medialib/mlib/Image
	at com.sun.media.jai.mlib.MediaLibAccessor$1.run(MediaLibAccessor.java:248)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.sun.media.jai.mlib.MediaLibAccessor.setUseMlib(MediaLibAccessor.java:245)
	at com.sun.media.jai.mlib.MediaLibAccessor.useMlib(MediaLibAccessor.java:177)
	at com.sun.media.jai.mlib.MediaLibAccessor.isMediaLibCompatible(MediaLibAccessor.java:357)
	at com.sun.media.jai.mlib.MediaLibAccessor.isMediaLibCompatible(MediaLibAccessor.java:315)
	at com.sun.media.jai.mlib.MlibScaleRIF.create(MlibScaleRIF.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at javax.media.jai.FactoryCache.invoke(FactoryCache.java:122)
	at javax.media.jai.OperationRegistry.invokeFactory(OperationRegistry.java:1674)
	at javax.media.jai.ThreadSafeOperationRegistry.invokeFactory(ThreadSafeOperationRegistry.java:473)
	at javax.media.jai.registry.RIFRegistry.create(RIFRegistry.java:332)
	at javax.media.jai.RenderedOp.createInstance(RenderedOp.java:819)
	at javax.media.jai.RenderedOp.createRendering(RenderedOp.java:867)
	at javax.media.jai.RenderedOp.getWidth(RenderedOp.java:2179)
	at com.sun.media.jai.widget.DisplayJAI.set(DisplayJAI.java:178)
	at cbit.vcell.geometry.gui.OverlayImageDisplayJAI.refreshImage(OverlayImageDisplayJAI.java:360)
	at cbit.vcell.geometry.gui.OverlayImageDisplayJAI.setUnderlyingImage(OverlayImageDisplayJAI.java:171)
	at cbit.vcell.geometry.gui.OverlayEditorPanelJAI$34.stateChanged(OverlayEditorPanelJAI.java:2495)
	at java.desktop/javax.swing.JSlider.fireStateChanged(JSlider.java:454)
	at java.desktop/javax.swing.JSlider$ModelListener.stateChanged(JSlider.java:369)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:371)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:309)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.setMaximum(DefaultBoundedRangeModel.java:226)
	at java.desktop/javax.swing.JSlider.setMaximum(JSlider.java:628)
	at cbit.vcell.geometry.gui.OverlayEditorPanelJAI.setImages(OverlayEditorPanelJAI.java:1284)
	at cbit.vcell.geometry.gui.ROIMultiPaintManager.updateUnderlayHistogramDisplay(ROIMultiPaintManager.java:3601)
	at cbit.vcell.geometry.gui.ROIMultiPaintManager.showGUI(ROIMultiPaintManager.java:755)
	at cbit.vcell.client.ClientRequestManager$22$1.run(ClientRequestManager.java:1965)
	at cbit.vcell.client.task.ClientTaskDispatcher.runTask(ClientTaskDispatcher.java:672)
	at cbit.vcell.client.task.ClientTaskDispatcher$1$2.run(ClientTaskDispatcher.java:384)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.sun.medialib.mlib.Image

**Comment by ACowan0105** [comment]
Also affects Geometry Editor directly:  
From a simulation with a 3D geometry, select edit image to open the geometry editor and the same problem appears.

**Comment by lesloew** [comment]
Repeating Jim's question: Is this issue resolved?

**Comment by ACowan0105** [comment]
Yes this is fixed.  Jim, can you close the issue? (I don't know if this needs a PR for when the Field Data fixes were originally made).

**Comment by ACowan0105** [comment]
Aberrant code from Frank's last changes to field data was disabled; this fixed the Gui issues with geometry editor in all places.  Larger issues related to field data - changing the interface and how field data is invoked and stored, are included in other issues:
#1462 
#1448 
#648 
#1034   (Epic)
#167
