### ISSUE TITLE
Make sure VCellSupport is contacted from "contact VCell Support" button in error messages

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#199]

**Comment by lesloew** [comment]
I found a way to reproducibly create this situation (in Alpha 48). Open the curated model: Ca_Release_Fink_etal_1999&2000. Try to 'Save as'; a null pointer exception appears and prompts the user to report the error. You can also produce an error when trying to change model units. Why the "Save as" doesn't work may be a separate bug.

**Comment by lesloew** [comment]
<SpatialObjects><SpatialObject Name="vobj_Extracellular0" Type="Volume" subVolume="Extracellular" regionId="0"><QuantityCategoryList><QuantityCategory Name="VolumeCentroid" Enabled="false" /><QuantityCategory Name="InteriorVelocity" Enabled="false" /><QuantityCategory Name="VolumeRegionSize" Enabled="true" /></QuantityCategoryList></SpatialObject><SpatialObject Name="vobj_Cytosol1" Type="Volume" subVolume="Cytosol" regionId="1"><QuantityCategoryList><QuantityCategory Name="VolumeCentroid" Enabled="false" /><QuantityCategory Name="InteriorVelocity" Enabled="false" /><QuantityCategory Name="VolumeRegionSize" Enabled="true" /></QuantityCategoryList></SpatialObject><SpatialObject Name="vobj_Nucleus2" Type="Volume" subVolume="Nucleus" regionId="2"><QuantityCategoryList><QuantityCategory Name="VolumeCentroid" Enabled="false" /><QuantityCategory Name="InteriorVelocity" Enabled="false" /><QuantityCategory Name="VolumeRegionSize" Enabled="true" /></QuantityCategoryList></SpatialObject><SpatialObject Name="sobj_Cytosol1_Extracellular0" Type="Surface" subVolumeInside="Cytosol" regionIdInside="1" subVolumeOutside="Extracellular" regionIdOutside="0"><QuantityCategoryList><QuantityCategory Name="SurfaceNormal" Enabled="false" /><QuantityCategory Name="SurfaceVelocity" Enabled="false" /><QuantityCategory Name="DistanceToSurface" Enabled="false" /><QuantityCategory Name="DirectionToSurface" Enabled="false" /><QuantityCategory Name="SurfaceSize" Enabled="true" /></QuantityCategoryList></SpatialObject><SpatialObject Name="sobj_Nucleus2_Cytosol1" Type="Surface" subVolumeInside="Nucleus" regionIdInside="2" subVolumeOutside="Cytosol" regionIdOutside="1"><QuantityCategoryList><QuantityCategory Name="SurfaceNormal" Enabled="false" /><QuantityCategory Name="SurfaceVelocity" Enabled="false" /><QuantityCategory Name="DistanceToSurface" Enabled="false" /><QuantityCategory Name="DirectionToSurface" Enabled="false" /><QuantityCategory Name="SurfaceSize" Enabled="true" /></QuantityCategoryList></SpatialObject></SpatialObjects>
<SpatialObjects><SpatialObject Name="vobj_Extracellular0" Type="Volume" subVolume="Extracellular" regionId="0"><QuantityCategoryList><QuantityCategory Name="VolumeCentroid" Enabled="false" /><QuantityCategory Name="InteriorVelocity" Enabled="false" /><QuantityCategory Name="VolumeRegionSize" Enabled="true" /></QuantityCategoryList></SpatialObject><SpatialObject Name="vobj_Cytosol1" Type="Volume" subVolume="Cytosol" regionId="1"><QuantityCategoryList><QuantityCategory Name="VolumeCentroid" Enabled="false" /><QuantityCategory Name="InteriorVelocity" Enabled="false" /><QuantityCategory Name="VolumeRegionSize" Enabled="true" /></QuantityCategoryList></SpatialObject><SpatialObject Name="vobj_Nucleus2" Type="Volume" subVolume="Nucleus" regionId="2"><QuantityCategoryList><QuantityCategory Name="VolumeCentroid" Enabled="false" /><QuantityCategory Name="InteriorVelocity" Enabled="false" /><QuantityCategory Name="VolumeRegionSize" Enabled="true" /></QuantityCategoryList></SpatialObject><SpatialObject Name="sobj_Cytosol1_Extracellular0" Type="Surface" subVolumeInside="Cytosol" regionIdInside="1" subVolumeOutside="Extracellular" regionIdOutside="0"><QuantityCategoryList><QuantityCategory Name="SurfaceNormal" Enabled="false" /><QuantityCategory Name="SurfaceVelocity" Enabled="false" /><QuantityCategory Name="DistanceToSurface" Enabled="false" /><QuantityCategory Name="DirectionToSurface" Enabled="false" /><QuantityCategory Name="SurfaceSize" Enabled="true" /></QuantityCategoryList></SpatialObject><SpatialObject Name="sobj_Nucleus2_Cytosol1" Type="Surface" subVolumeInside="Nucleus" regionIdInside="2" subVolumeOutside="Cytosol" regionIdOutside="1"><QuantityCategoryList><QuantityCategory Name="SurfaceNormal" Enabled="false" /><QuantityCategory Name="SurfaceVelocity" Enabled="false" /><QuantityCategory Name="DistanceToSurface" Enabled="false" /><QuantityCategory Name="DirectionToSurface" Enabled="false" /><QuantityCategory Name="SurfaceSize" Enabled="true" /></QuantityCategoryList></SpatialObject></SpatialObjects>
jscl.text.ParseException
	at jscl.text.BracketedExpression.parse(BracketedExpression.java:32)
	at jscl.text.PrimaryExpression.parse(ExpressionParser.java:345)
	at jscl.text.UnsignedExponent.parse(ExpressionParser.java:292)
	at jscl.text.UnsignedFactor.parse(ExpressionParser.java:183)
	at jscl.text.TermParser.parse(ExpressionParser.java:100)
	at jscl.text.ExpressionParser.parse(ExpressionParser.java:30)
	at jscl.math.Expression.valueOf(Expression.java:590)
	at cbit.vcell.biomodel.ModelUnitConverter.createBioModelWithNewUnitSystem(ModelUnitConverter.java:88)
	at cbit.vcell.client.desktop.biomodel.BioModelParametersPanel.changeUnitsButtonPressed(BioModelParametersPanel.java:413)
	at cbit.vcell.client.desktop.biomodel.BioModelParametersPanel$InternalEventHandler.actionPerformed(BioModelParametersPanel.java:354)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
JSCL couldn't parse "(6.02214179E17 * underscore2DcorrunderscorePM * Jch * ( - Caunderscorecytosol + Caunderscoreextracellula) * (t > T1) * (t < T2))"
java.lang.NullPointerException
	at cbit.vcell.client.DocumentWindowManager.setDocumentID(DocumentWindowManager.java:391)
	at cbit.vcell.client.BioModelWindowManager.resetDocument(BioModelWindowManager.java:419)
	at cbit.vcell.client.desktop.biomodel.BioModelParametersPanel.changeUnitsButtonPressed(BioModelParametersPanel.java:414)
	at cbit.vcell.client.desktop.biomodel.BioModelParametersPanel$InternalEventHandler.actionPerformed(BioModelParametersPanel.java:354)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
java.lang.NullPointerException
	at cbit.vcell.client.task.NewName.run(NewName.java:51)
	at cbit.vcell.client.task.ClientTaskDispatcher.runTask(ClientTaskDispatcher.java:662)
	at cbit.vcell.client.task.ClientTaskDispatcher.access$600(ClientTaskDispatcher.java:55)
	at cbit.vcell.client.task.ClientTaskDispatcher$1$2.run(ClientTaskDispatcher.java:375)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by lesloew** [comment]
see stack trace above.

**Comment by lesloew** [comment]
A good way to generate this is to try to cut and paste a reaction from one model to another

**Comment by jcschaff** [comment]
current implementation tries to post an email directly from the VCell client to a UCHC SMTP server.  This server is not accessible (and should not be publicly available).

Need to add a /contactus endpoint on the vcell-api and have the client post to it (vcell-api can talk to our SMTP server safely).
