### ISSUE TITLE
mvn clean install dependency:copy-dependencies fails on "Running org.vcell.vcellij.api.SimulationServiceImplTest" in Ubuntu 17.10

### ISSUE THREAD

**Issue by cirosantilli** [virtualcell/vcell#4]
7e2ffe2059cb9057e7d5c42eaa995e50bd1fb76f

I'll try Docker later. It would be awesome if there was an example that shows how to run something interesting and get interesting results out, with zero effort.

```
Running org.vcell.vcellij.api.SimulationServiceImplTest
 WARN (Model.java:4805) - registerIds: the object org.sbml.jsbml.ext.spatial.CompartmentMapping is neither a UniqueNamedSBase, a LocalParameter or a UnitDefinition so its id will not be registered in the Model.
 WARN (Model.java:4805) - registerIds: the object org.sbml.jsbml.ext.spatial.CompartmentMapping is neither a UniqueNamedSBase, a LocalParameter or a UnitDefinition so its id will not be registered in the Model.
 WARN (Model.java:4805) - registerIds: the object org.sbml.jsbml.ext.spatial.CompartmentMapping is neither a UniqueNamedSBase, a LocalParameter or a UnitDefinition so its id will not be registered in the Model.
ERROR (SpatialModelPlugin.java:266) - The spatial id "EC" is already present in the spatial model assigned to the model optoPlexin_PRG_rule_based_1_Dimensional. The new element will not be added to the model.
ERROR (IdentifierException.java:75) - An element with the metaid "EC" is already present in the SBML document. The element analyticVolume will not be annotated with it.
 WARN (AnalyticVolume.java:394) - Could not recognized the value EC for the attribute id on the 'analyticVolume' element.
ERROR (SpatialModelPlugin.java:266) - The spatial id "Cyt" is already present in the spatial model assigned to the model optoPlexin_PRG_rule_based_1_Dimensional. The new element will not be added to the model.
ERROR (IdentifierException.java:75) - An element with the metaid "Cyt" is already present in the SBML document. The element analyticVolume will not be annotated with it.
 WARN (AnalyticVolume.java:394) - Could not recognized the value Cyt for the attribute id on the 'analyticVolume' element.
 WARN (SBMLCoreParser.java:386) - No UnitDefinition matches the unitsID 'um3' of compartment 'Cyt'.
 WARN (SBMLCoreParser.java:386) - No UnitDefinition matches the unitsID 'um3' of compartment 'EC'.
SBML 'item' unit found, interpreted as 'molecule'
SBML 'item' unit found, interpreted as 'molecule'
SBML 'item' unit found, interpreted as 'molecule'
MembraneMapping.getTotalVolumeCorrection(): volume correction for a resolved membrane is meaningless, but maybe a 1.0 would be harmless
MathMapping.refresh Start
PotentialMapping.getTotalMembraneCurrent(): ASSUMING NO MEMBRANE CURRENTS IF 'CALCULATE_VOLTAGE' == false
MathMapping.refresh End
<SpatialObjects><SpatialObject Name="vobj_EC0" Type="Volume" subVolume="EC" regionId="0"><QuantityCategoryList><QuantityCategory Name="VolumeCentroid" Enabled="false" /><QuantityCategory Name="InteriorVelocity" Enabled="false" /><QuantityCategory Name="VolumeRegionSize" Enabled="true" /></QuantityCategoryList></SpatialObject><SpatialObject Name="vobj_Cyt1" Type="Volume" subVolume="Cyt" regionId="1"><QuantityCategoryList><QuantityCategory Name="VolumeCentroid" Enabled="false" /><QuantityCategory Name="InteriorVelocity" Enabled="false" /><QuantityCategory Name="VolumeRegionSize" Enabled="true" /></QuantityCategoryList></SpatialObject><SpatialObject Name="sobj_Cyt1_EC0" Type="Surface" subVolumeInside="Cyt" regionIdInside="1" subVolumeOutside="EC" regionIdOutside="0"><QuantityCategoryList><QuantityCategory Name="SurfaceNormal" Enabled="false" /><QuantityCategory Name="SurfaceVelocity" Enabled="false" /><QuantityCategory Name="DistanceToSurface" Enabled="false" /><QuantityCategory Name="DirectionToSurface" Enabled="false" /><QuantityCategory Name="SurfaceSize" Enabled="true" /></QuantityCategoryList></SpatialObject></SpatialObjects>
-----Setting executable LD_LIBRARY_PATH to /usr/lib:/usr/local/lib:/usr/local/lib64:/home/ciro/git/vcell/vcell-core/../localsolvers/linux64
/home/ciro/git/vcell/vcell-core/../localsolvers/linux64/FiniteVolume_x64: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory


(/home/ciro/git/vcell/vcell-core/../localsolvers/linux64/FiniteVolume_x64 /home/ciro/.vcell/simdata/temp/SimID_561491369_0_.fvinput)
org.vcell.util.DataAccessException: simulation data for [VCSimulationIdentifier[561491369,0,temp(123)]] newStyle=SimID_561491369_0_.log oldStyle=SimID_561491369.log not exist in primary /home/ciro/.vcell/simdata/temp dir or secondary null dir or Archive server.
        at cbit.vcell.simdata.DataSetControllerImpl.getDataSetTimes(DataSetControllerImpl.java:2879)
        at org.vcell.vcellij.SimulationServiceImpl.getDataSetController(SimulationServiceImpl.java:383)
        at org.vcell.vcellij.SimulationServiceImpl.getVariableList(SimulationServiceImpl.java:446)
        at org.vcell.vcellij.api.SimulationServiceImplTest.test(SimulationServiceImplTest.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
java.lang.RuntimeException: failed to read dataset: simulation data for [VCSimulationIdentifier[561491369,0,temp(123)]] newStyle=SimID_561491369_0_.log oldStyle=SimID_561491369.log not exist in primary /home/ciro/.vcell/simdata/temp dir or secondary null dir or Archive server.
        at org.vcell.vcellij.SimulationServiceImpl.getDataSetController(SimulationServiceImpl.java:388)
        at org.vcell.vcellij.SimulationServiceImpl.getVariableList(SimulationServiceImpl.java:446)
        at org.vcell.vcellij.api.SimulationServiceImplTest.test(SimulationServiceImplTest.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.6 sec <<< FAILURE! - in org.vcell.vcellij.api.SimulationServiceImplTest
test(org.vcell.vcellij.api.SimulationServiceImplTest)  Time elapsed: 1.6 sec  <<< ERROR!
java.lang.Exception: failed to retrieve variable list: failed to read dataset: simulation data for [VCSimulationIdentifier[561491369,0,temp(123)]] newStyle=SimID_561491369_0_.log oldStyle=SimID_561491369.log not exist in primary /home/ciro/.vcell/simdata/temp dir or secondary null dir or Archive server.
        at org.vcell.vcellij.api.SimulationServiceImplTest.test(SimulationServiceImplTest.java:61)


Results :

Tests in error:
  SimulationServiceImplTest.test:61 »  failed to retrieve variable list: failed ...

Tests run: 45, Failures: 0, Errors: 1, Skipped: 14

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Virtual Cell Project ............................... SUCCESS [ 19.480 s]
[INFO] ojdbc6 ............................................. SUCCESS [  0.489 s]
[INFO] ucp ................................................ SUCCESS [  0.015 s]
[INFO] vcell-util ......................................... SUCCESS [ 15.501 s]
[INFO] vcell-math ......................................... SUCCESS [  7.538 s]
[INFO] vcell-apiclient .................................... SUCCESS [ 15.302 s]
[INFO] vcell-core ......................................... FAILURE [02:29 min]
[INFO] vcell-client ....................................... SKIPPED
[INFO] vcell-server ....................................... SKIPPED
[INFO] vcell-vmicro ....................................... SKIPPED
[INFO] vcell-oracle ....................................... SKIPPED
[INFO] vcell-admin ........................................ SKIPPED
[INFO] vcell-api .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:38 min
[INFO] Finished at: 2018-04-01T17:27:33+01:00
[INFO] Final Memory: 105M/2547M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project vcell-core: There are test failures.
[ERROR]
[ERROR] Please refer to /home/ciro/git/vcell/vcell-core/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :vcell-core
~/git/vcell
```

Then if I try to run:

```
./vcell.sh
```

it fails with:

```
java -Dvcell.installDir=/home/ciro/git/vcell -Dvcell.softwareVersion=standalone_VCell_7.0 -Dvcell.bioformatsJarFileName=vcell-bioformats-0.0.1-SNAPSHOT-jar-with-dependencies.jar -Dvcell.bioformatsJarDownloadURL=http://vcell.org/webstart/vcell-bioformats-0.0.1-SNAPSHOT-jar-with-dependencies.jar -cp ./vcell-client/target/maven-jars/*:./vcell-client/target/* cbit.vcell.client.test.VCellClientTest vcellapi.cam.uchc.edu:443
Error: Could not find or load main class cbit.vcell.client.test.VCellClientTest
```

**Comment by cirosantilli** [comment]
Was it fixed?

**Comment by gmarupilla** [comment]
You need to use oracle JDK 1.8 to compile whole project.

**Comment by gmarupilla** [comment]
Please follow the instructions from [here](https://github.com/virtualcell/vcell/blob/cb70c827cfce560a04556e8d11744bd961a87871/.github/workflows/ci_cd.yml#L29) for installing the requirements.

**Comment by cirosantilli** [comment]
Thanks for the info GMarupilla, feel free to close if you feel this is solved, I don't have time to reproduce currently, cheers.
