### ISSUE TITLE
BUG: VCell fails to generate CSV tables for SED-ML plot data when no dataset is available in another report for each data generator of each curve/surface

### ISSUE THREAD

**Issue by jonrkarr** [virtualcell/vcell#80]
[Example COMBINE archive](https://github.com/virtualcell/vcell/files/6850324/example.zip)

```
Traceback (most recent call last):
  File "/usr/local/app/vcell/installDir/python/vcell_cli_utils/vcell_cli_utils/cli.py", line 372, in <module>
    fire.Fire({
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/app/vcell/installDir/python/vcell_cli_utils/vcell_cli_utils/cli.py", line 327, in gen_plot_pdfs
    all_report_dataref, all_plot_curves = update_dataref_with_report_label(
  File "/usr/local/app/vcell/installDir/python/vcell_cli_utils/vcell_cli_utils/cli.py", line 285, in update_dataref_with_report_label
    new_ref['y'] = get_report_label_from_data_ref(
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jonrkarr** [comment]
The problematic function `get_report_label_from_data_ref` doesn't need to be fixed. Rather, it should be removed (see #81) so that plot data is saved independently from any SED-ML reports that also happen to be defined.

**Comment by jonrkarr** [comment]
I think this can be closed.
